### PR TITLE
[5.0] MSPB-160: Remove default feature codes config enforcer

### PR DESCRIPTION
**Pull request by azefiel**

### CODE REVIEW

**Review by masmerino13 — APPROVED** [review]
Thanks, seems those methods aren't used at any place

**Comment by azefiel** [comment]
@masmerino13 which methods are you referring to?

**Comment by masmerino13** [comment]
I'm talking about `maybeDeleteMalformedFeatureCodes` and `isMalformed` @azefiel

**Comment by azefiel** [comment]
`isMalformed ` was used by `maybeDeleteMalformedFeatureCodes` to resolve which callflows, if any, to delete. And `maybeDeleteMalformedFeatureCodes` was one of the tasks run in series to clean up existing callflows when checking if all SmartPBX feature code callflows existed.

That's my understanding of it anyways but please share your point of view as to why those where not used.

**Comment by masmerino13** [comment]
I don't have any point to share, your commit is removing code here, so, I just did a comment nothing else, I you're removing it it's fine to me, that's all :)

**Comment by azefiel** [comment]
Okay, apologies for misunderstanding your first comment then 😅

**Pull request merged**
