### PR TITLE
UI-3311: Allow user to choose which main number to set for E911

### PR DESCRIPTION
**Pull request by guillegr123**

### CODE REVIEW

**Comment by azefiel** [comment]
When my account has two main numbers with e911 configured for each, and I remove e911 from one of the number, the e911 number selection popup appears.

The problem is that my other main number still has e911 configured so I would not expect the popup to show in that use case.

**Comment by guillegr123** [comment]
I changed the behavior to set the remaining E911 as the account emergency number automatically without displaying the choose popup dialog, if there is only that one left after removing the E911 from the current account emergency number.

**Comment by azefiel** [comment]
Nice!

A bit too much of hand holding in my opinion but maybe that's what users need ;)

**Comment by guillegr123** [comment]
That's what makes 2600Hz different and user friendly :wink:

**Pull request merged**
