### PR TITLE
Add group feature: ring group toggle

### PR DESCRIPTION
**Pull request by mira-t**
Allows users to enable logging in and out of a group via a group feature. The user specifies the extensions for logging in and out of the group.

### CODE REVIEW

**Comment by mira-t** [comment]
@JRMaitre Hi could you please have a look at this for me?

**Comment by JRMaitre** [comment]
Yes we have to check with product to see if they want to add this to the Smart PBX app. I'll let you know when I know more!

**Comment by JRMaitre** [comment]
After talking with product, it's not something they want to expose in SmartPBX for now, sorry about that :(

**Comment by kalda341** [comment]
@JRMaitre What if we make the display of this feature configurable in config.js?

**Pull request closed without merging**
